# Copyright 2018 Province of British Columbia
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and limitations under the License.

# Repo estimates unreported mortality for each GBPU based on:
# 1. core security (in % by GBPU). Note: replaces previous statistic of % capable within 50km of areas with >5000 people
# 2. Hunter day density -> HunterDensity repo: https://github.com/bcgov/HunterDensity
# Note: previously used Large Ungulate harvest replaced by hunter day density above
# 3. frontcountry (in % by GBPU) - from provincial CE Grizzly protocol. Note: replaces previous statistic of % capable habitat with roads

source("header.R")

GBPU_lutFile <- file.path(StrataDir,"GBPU_lut")
GBPU_lut <- readRDS(file = GBPU_lutFile)
colnames(GBPU_lut)<-c('GBPUid','GBPU')

#Read in current female mortality data based compiled by Steve McIver and Provincial Grizzly Bear Technical Team
#Includes 2018 updated population information
# Select the population size and Average Annual Female mortality Reported 10 year average
#Mort <- data.frame(read_xlsx(file.path(DataDir, "Female Mort_GBPU_V3.xlsx"), sheet=NULL)) %>%
#           dplyr::select(GBPU=GBPU, PopEst=Pop.Est, ReportedFemaleMort=Average.Annual.Reported..11) %>%
#           join(GBPU_lut, by='GBPU')

StrataL <- c('GBPUr','GBPUr_NonHab','GBPUr_BEI_1_2','GBPUr_BEI_1_5')
num<-length(StrataL)

#Read in unreported mortality data from excel generated by the repo GB_Unreproted - 04_output_RevisedRanking.R
UnrepLR<-list()
for (i in 1:num) {
  StratName<-StrataL[i]
  # Read in strata sheet and modify so GBPUs consistent with current 55 GBPUs
  # North Purcells = North Purcells + Spillamacheen
  # Central-South Purcells = South Purcells + Central Purcells
  # Drop those records since new has recalculated values based on 55
  UnrepLR[[i]] <-
    data.frame(read_xls(file.path(UnRepDataDir,paste('UnReportedV2.xls',sep='')), sheet=StratName)) %>%
    mutate(UnReportRatio=UnReportDensity) %>%
      dplyr::select(GBPU,UnReportRatio)
  }

#select the full GBPU for now - 'GBPUr'
UnReport<-UnrepLR[[1]]

#Read in spatial files for output
GBPUr<-raster(file.path(StrataDir,"GBPUr.tif"))
GBPU<-st_read(file.path(GBspatialDir,'GBPU.shp'))
GBPU_lut<-readRDS(file = file.path(StrataDir,'GBPU_lut'))
colnames(GBPU_lut)<-c('GBPU','GBPU_Name')

WMUr<-raster(file.path(StrataDir,"WMUr.tif"))
WMU<-st_read(file.path(GBspatialDir,'WMU.shp'))

#Load CI data
#GB_CI <- data.frame(read_xlsx(file.path(DataDir, "CI/GB_CI_to_2018.xlsx"), sheet=NULL))
GB_CI <- data.frame(read_xlsx(file.path(DataDir, "CI/CI-1978-2017_Don.xlsx"), sheet=NULL))

#Load grizzly bear population data
gb2018popIN <- data.frame(read_xlsx(file.path(GBDataDir, "population/GB2018pop.xlsx"), sheet=NULL))
gb2018pop<-merge(GBPU_lut,gb2018popIN, by.x='GBPU_Name', by.y='GBPU')
